#!/usr/bin/env ruby
# Generates an offline C++ catalog from shared HUD translations and Windows text.
require 'json'
root = File.expand_path('../..', __dir__)
shared = JSON.parse(File.read(File.join(root, 'overlay/HUDLocalizations.json')))
dictionary = shared.transform_values { |v| [v.fetch('en'), v.fetch('ja'), v.fetch('ko')] }
chinese = {}
File.foreach(File.join(root, 'windows/localizations.tsv')) do |line|
  next if line.start_with?('#') || line.strip.empty?
  fields = line.chomp.split("\t", -1)
  abort "Invalid localization row" unless [4,5].include?(fields.size) && fields.all? { |v| !v.empty? }
  if fields.size == 5
    chinese[fields[0]] = fields[1]
    dictionary[fields[0]] = [fields[2],fields[3],fields[4]]
  else
    dictionary[fields[0]] = fields.drop(1)
  end
end
decode = ->(s) { s.gsub('\\r', "\r").gsub('\\n', "\n").gsub('\\t', "\t").gsub('\\"', '"').gsub('\\\\', '\\') }
literals = Dir[File.join(root,'windows/src/**/*.cpp')].flat_map do |path|
  File.read(path).scan(/L"(?:\\.|[^"\\])*"(?:\s*L"(?:\\.|[^"\\])*")*/).map { |group|
    group.scan(/L"((?:\\.|[^"\\])*)"/).flatten.map(&decode).join
  }
end.uniq
# Segment only developer-owned literals, before substitution into live strings.
# Separators preserve whitespace, line breaks and existing layout.
missing = []
translate = lambda do |source, index|
  return dictionary[source][index] if dictionary.key?(source)
  chunks = source.split(/(\r\n|\n|[ \t]+\|[ \t]+|[ \t]*·[ \t]*)/, -1)
  chunks.map do |chunk|
    stripped = chunk.strip
    if dictionary.key?(stripped)
      chunk.sub(stripped, dictionary[stripped][index])
    elsif stripped.empty? || !stripped.match?(/\p{Han}/)
      chunk
    else
      missing << stripped
      chunk
    end
  end.join
end
quote = ->(s) { 'L' + JSON.generate(s).gsub('\\/', '/') }
rows = literals.select { |s| (s.match?(/\p{Han}/) || chinese.keys.any? { |k| s.include?(k) }) && !%w[简体中文 繁體中文 日本語].include?(s) }
result = "// Generated by windows/tests/generate_localizations.rb; do not edit.\n#pragma once\nnamespace codex_monitor {\nstruct HudTranslation { const wchar_t *source, *zh, *en, *ja, *ko; };\ninline const HudTranslation kHudTranslations[]{\n"
rows.each do |s|
  zh = s.split(/(\r\n|\n|[ \t]+\|[ \t]+|[ \t]*·[ \t]*)/, -1).map { |c| chinese.key?(c.strip) ? c.sub(c.strip,chinese[c.strip]) : c }.join
  result << '{' + [s,zh,translate.call(s,0),translate.call(s,1),translate.call(s,2)].map(&quote).join(',') + "},\n"
end
abort "Missing translations:\n#{missing.uniq.join("\n")}" unless missing.empty?
result << "};\n}\n"
target = File.join(root,'windows/src/localization_catalog.h')
if ARGV.include?('--check')
  abort 'Generated localization catalog is stale' unless File.exist?(target) && File.read(target) == result
else
  File.write(target, result)
end
puts "#{rows.size} Windows literals: English/Japanese/Korean coverage checked"
