#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSDictionary<NSString *, id> *CodexCalendarUsage(NSArray *buckets, NSDate *now);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CodexActivityStateFromJSONLLines(NSArray<NSString *> *lines, NSDate *modifiedAt, NSDate *now);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CodexActivityStateFromJSONLLinesWithFallback(NSArray<NSString *> *lines, NSDate *modifiedAt, NSDate *now, NSDate *fallbackStart);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CodexNormalizedThreadMetadata(NSDictionary *thread);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CodexScanRecentActivityAtRoot(NSDictionary<NSString *, NSDictionary *> *metadataByID, NSDate *now, NSURL *root);

@interface CodexStatusSnapshot : NSObject
@property(nonatomic) BOOL quotaAvailable;
@property(nonatomic) NSTimeInterval quotaUpdatedAt;
@property(nonatomic, copy) NSString *quotaErrorText;
@property(nonatomic, copy) NSDictionary<NSString *, NSString *> *interfaceFailureKinds;
@property(nonatomic, strong) NSNumber *ordinaryUsageAllowed;
@property(nonatomic) NSTimeInterval ordinaryUsageUpdatedAt;
@property(nonatomic) BOOL fiveHourAvailable;
@property(nonatomic) double fiveHourRemainingPercent;
@property(nonatomic) NSTimeInterval fiveHourResetAt;
@property(nonatomic) double fiveHourWindowDurationMins;
@property(nonatomic, copy) NSString *fiveHourDataState;
@property(nonatomic) BOOL weeklyAvailable;
@property(nonatomic) double weeklyRemainingPercent;
@property(nonatomic) NSTimeInterval weeklyResetAt;
@property(nonatomic) double weeklyWindowDurationMins;
@property(nonatomic, copy) NSString *weeklyDataState;
@property(nonatomic, copy) NSString *rateLimitReachedType;
@property(nonatomic) BOOL rateLimitResetCreditsAvailable;
@property(nonatomic) NSInteger rateLimitResetCreditsCount;
@property(nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> *rateLimitBuckets;
@property(nonatomic) BOOL accountAvailable;
@property(nonatomic, copy) NSString *planType;
@property(nonatomic) NSTimeInterval accountUpdatedAt;
@property(nonatomic, copy) NSString *accountErrorText;
@property(nonatomic) BOOL usageAvailable;
@property(nonatomic) NSTimeInterval usageUpdatedAt;
@property(nonatomic, copy) NSString *usageErrorText;
@property(nonatomic) long long todayTokens;
@property(nonatomic) BOOL todayUsageAvailable;
@property(nonatomic) long long sevenDayTokens;
@property(nonatomic) long long previousSevenDayTokens;
@property(nonatomic) long long thirtyDayTokens;
@property(nonatomic) long long monthToDateTokens;
@property(nonatomic) long long monthForecastTokens;
@property(nonatomic, copy) NSString *latestUsageDate;
@property(nonatomic) long long latestUsageTokens;
@property(nonatomic) long long lifetimeTokens;
@property(nonatomic) BOOL peakDailyTokensAvailable;
@property(nonatomic) long long peakDailyTokens;
@property(nonatomic) NSInteger currentStreakDays;
@property(nonatomic) BOOL longestRunningTurnAvailable;
@property(nonatomic) NSInteger longestRunningTurnSec;
@property(nonatomic) BOOL longestStreakAvailable;
@property(nonatomic) NSInteger longestStreakDays;
@property(nonatomic) BOOL modelQuotaAvailable;
@property(nonatomic, copy) NSString *modelQuotaName;
@property(nonatomic) double modelQuotaRemainingPercent;
@property(nonatomic) NSTimeInterval modelQuotaResetAt;
@property(nonatomic, copy) NSString *modelQuotaWindowLabel;
@property(nonatomic) BOOL activityAvailable;
@property(nonatomic) NSTimeInterval activityUpdatedAt;
@property(nonatomic, copy) NSString *activityErrorText;
@property(nonatomic) BOOL activityPartial;
@property(nonatomic, copy) NSString *activityNoteText;
@property(nonatomic) NSInteger unresolvedRecentTaskCount;
@property(nonatomic) NSInteger activeTaskCount;
@property(nonatomic) NSInteger longestActiveTaskSec;
@property(nonatomic, copy) NSArray<NSString *> *activeTaskNames;
@property(nonatomic) BOOL recentTasksAvailable;
@property(nonatomic) NSTimeInterval recentTasksUpdatedAt;
@property(nonatomic, copy) NSString *recentTasksErrorText;
@property(nonatomic) NSInteger recentTaskCount;
@property(nonatomic) NSInteger recentTaskProjectCount;
@property(nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> *recentTasks;
@property(nonatomic) BOOL livePerTaskUsageAvailable;
@property(nonatomic) BOOL localCostAvailable;
@property(nonatomic) NSTimeInterval localCostUpdatedAt;
@property(nonatomic, copy) NSString *localCostErrorText;
@property(nonatomic) BOOL localCostScanIncomplete;
@property(nonatomic) NSTimeInterval localCostTrackingStartedAt;
@property(nonatomic) NSTimeInterval localTokenBucketsStartedAt;
@property(nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> *localTokenBuckets;
@property(nonatomic) long long localTodayTokens;
@property(nonatomic) long long localSevenDayTokens;
@property(nonatomic) long long localThirtyDayTokens;
@property(nonatomic) double localTodayCostUSD;
@property(nonatomic) double localSevenDayCostUSD;
@property(nonatomic) double localThirtyDayCostUSD;
@property(nonatomic) double localMonthCostUSD;
@property(nonatomic) double localMonthForecastCostUSD;
@property(nonatomic) double localPricedTokenPercent;
@property(nonatomic, copy) NSString *localTopModel;
@property(nonatomic, copy) NSArray<NSNumber *> *localDailyTokenTrend;
@property(nonatomic) BOOL fiveHourForecastAvailable;
@property(nonatomic, copy) NSString *fiveHourForecastHeadline;
@property(nonatomic, copy) NSString *fiveHourForecastDetail;
@property(nonatomic) BOOL weeklyForecastAvailable;
@property(nonatomic, copy) NSString *weeklyForecastHeadline;
@property(nonatomic, copy) NSString *weeklyForecastDetail;
@property(nonatomic) BOOL weeklyRolling24hConsumptionAvailable;
@property(nonatomic) double weeklyRolling24hConsumedPercent;
@property(nonatomic) BOOL weeklyNaturalDayConsumptionAvailable;
@property(nonatomic) double weeklyNaturalDayConsumedPercent;
@property(nonatomic) NSTimeInterval updatedAt;
@property(nonatomic, copy) NSString *statusText;
@end

@interface CodexStatusProvider : NSObject
@property(nonatomic, readonly) CodexStatusSnapshot *snapshot;
@property(nonatomic, readonly) NSTimeInterval recommendedRetryInterval;
@property(nonatomic, copy) void (^updateHandler)(void);
@property(nonatomic) BOOL costHistoryEnabled;
@property(nonatomic) BOOL quotaForecastEnabled;
@property(nonatomic) BOOL accountDataEnabled;
- (void)start;
- (void)refreshQuota;
- (void)refreshQuotaInBackground;
- (void)refreshActivity;
- (void)refreshCostHistory;
- (void)stop;
@end
